version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-eventsapi
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "3v3nts@pI.NET"
    ports:
      - "1344:1433"
    volumes:
      - sql_data:/var/opt/mssql
    restart: always

volumes:
  sql_data:
